<?php

namespace App\Filament\Resources\Donors\Pages;

use App\Filament\Resources\Donors\DonorResource;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\Support\Htmlable;

class CreateDonor extends CreateRecord
{
    protected static string $resource = DonorResource::class;


    public function getTitle(): string|Htmlable
    {
        return "ایجاد خیر جدید"; // TODO: Change the autogenerated stub
    }
}
