<?php

namespace App\Filament\Resources\Donors\Pages;

use App\Filament\Resources\Donors\DonorResource;
use Filament\Actions\DeleteAction;
use Filament\Resources\Pages\EditRecord;
use Illuminate\Contracts\Support\Htmlable;

class EditDonor extends EditRecord
{
    protected static string $resource = DonorResource::class;

    protected function getHeaderActions(): array
    {
        return [
            DeleteAction::make()->label(__("donor.panel.delete_label")),
        ];
    }

    public function getTitle(): string|Htmlable
    {
        return __("donor.panel.edit_label"); // TODO: Change the autogenerated stub
    }

    public function getBreadcrumb(): string
    {
        return __("donor.panel.edit_label"); // TODO: Change the autogenerated stub
    }
}
